name: blue
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^2.1.14
  flutter_icons: ^1.1.0
  cloud_firestore: ^0.16.0
  firebase_auth: 
  flutter_local_notifications: ^3.0.3
  google_sign_in: ^4.4.1
  cached_network_image: ^2.2.0+1
  image_picker: ^0.6.5+1
  firebase_storage:
  intl: ^0.16.1
  timeago: ^2.0.26
  video_player: ^0.10.8+1
  flutter_video_compress: ^0.3.7+8
  provider: ^4.1.2
  video_thumbnail: ^0.2.1
  firebase_database:
  carousel_pro: ^1.0.0
  link_previewer: ^1.2.1
  multi_image_picker: ^4.7.15
  giphy_client: ^0.2.0
  url_launcher: ^5.7.10
  flutter_linkify: ^3.1.3
  simple_image_crop: ^0.1.3
  video_compress: ^2.0.0
  full_screen_image: ^1.0.2
  flutter_clipboard_manager: ^0.0.2
  flutter_ffmpeg: ^0.2.10
  image_downloader: ^0.20.0
  flutter_cache_manager: ^1.4.1
  device_info: ^0.4.2+4
  flutter_email_sender: ^3.0.1
  webview_flutter: ^1.0.7
  flick_video_player: ^0.1.1
  visibility_detector: ^0.1.5
  flutter_link_preview: ^1.2.11
  fluentui_system_icons: ^1.1.85
  animations: ^1.1.2
  firebase_dynamic_links: 
  firebase_core: ^0.7.0
  package_info: ^0.4.3+2
  page_transition: ^1.1.7+3
  sortedmap: ^0.4.2+1
  flutter_svg: ^0.18.0
  nuts_activity_indicator: ^0.1.1
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  path_provider: ^1.6.24
  sticky_headers: ^0.1.8+1
  import_sorter: ^4.4.1
  share: ^0.6.5+4
  string_validator: ^0.1.4
  hasura_connect: ^2.0.1
  firebase_messaging:
  hive_cache_interceptor: ^1.0.0-dev.2
  auth_buttons: ^0.0.4
  blurhash_dart: ^0.2.3
  flutter_blurhash: ^0.5.0
  flash: ^1.3.2
  ars_progress_dialog: ^0.1.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test: 
    sdk: flutter
                                                    
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/icons/appbar_appicon.png
   - assets/icons/appbar_appicon_inverted.png
   - assets/icons/google_signin_button.png
   - assets/icons/google_sign_in_button.png
   - assets/images/appicon_rays.png
   - assets/icons/seperation_dot_icon.svg
   - assets/images/GIPHY_light.png
   - assets/images/GIPHY_dark.png
   - assets/images/Earth and Moon.svg
   - assets/images/Bad Gateway.svg
   - assets/images/No messages.svg
   - assets/images/Welcome.svg
   - assets/images/Message Sent.svg
   - assets/images/Searching.svg
   - assets/images/placeholder_image.jpg
   - assets/images/stark-bnb-icon-wa.png
   - assets/images/stark-bnb-icon-wi.png
   - assets/images/sign_in_image.png
   - assets/images/sign_in_image_w.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Techna Sans Regular
      fonts:
        - asset: assets/fonts/TechnaSansRegular.ttf
    - family: Diskopia
      fonts:
        - asset: assets/fonts/Diskopia.ttf
    - family: Foo
      fonts:
        - asset: assets/fonts/Foo.ttf      
    - family: LostFish
      fonts:
        - asset: assets/fonts/LostFish.ttf
    - family: Georgia
      fonts:
        - asset: assets/fonts/Georgia.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
    - family: Yahoo Sans
      fonts:
        - asset: assets/fonts/yahoo_sans_regular.ttf
          weight: 400
        - asset: assets/fonts/yahoo_sans_medium.ttf
          weight: 500
    - family: Yahoo Sans Cond
      fonts:
        - asset: assets/fonts/yahoo_sans_cond_black.ttf
    - family: Lexend Deca
      fonts:
        - asset: assets/fonts/LexendDeca-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
