name: blue
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.18+19

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^3.0.2
  flutter_icons: ^1.1.0
  cloud_firestore: ^2.0.0
  firebase_auth: ^1.2.0
  flutter_local_notifications: ^6.0.0                       #
  google_sign_in: ^5.0.4
  cached_network_image: ^3.0.0             #
  image_picker: ^0.6.5+1
  firebase_storage: ^8.0.1
  intl: ^0.17.0
  timeago: ^2.0.26
  video_player: ^2.1.3
  flick_video_player: ^0.3.1
  provider: ^5.0.0
  video_thumbnail: ^0.2.1    #
  firebase_database: ^6.0.0  #
  carousel_pro: ^1.0.0
  multi_image_picker: ^4.7.15    #
  url_launcher: ^6.0.4
  flutter_linkify: ^3.1.3
  video_compress: ^3.0.0         #
  full_screen_image: ^1.0.2
  flutter_clipboard_manager: ^0.0.2   #
  image_downloader: ^0.20.0     #
  flutter_cache_manager: ^3.0.2   #
  device_info: ^0.4.2+4    #
  flutter_email_sender: ^3.0.1   #
  webview_flutter: ^2.0.4      #
  visibility_detector: ^0.1.5      
  fluentui_system_icons: ^1.1.106
  animations: ^1.1.2
  firebase_dynamic_links: ^2.0.0    #
  firebase_core: ^1.1.0
  package_info: ^0.4.3+2     #
  page_transition: ^1.1.7+3
  sortedmap: ^0.5.0
  flutter_svg: ^0.22.0          #
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  path_provider: ^2.0.0      #
  sticky_headers: ^0.1.8+1
  import_sorter: ^4.4.1         ##
  share: ^2.0.1                #
  string_validator: ^0.2.0-nullsafety.0
  hasura_connect: ^3.0.2
  firebase_messaging: ^10.0.0
  # hive_cache_interceptor: ^1.0.0-dev.3
  blurhash_dart: ^0.2.3
  flutter_blurhash: ^0.6.0
  flash: ^1.3.2
  ars_progress_dialog: ^0.1.2
  flutter_login: ^2.0.0-nullsafety.0
  argon_buttons_flutter: ^1.0.6
  graphql_flutter: ^5.0.0-nullsafety.5      #
  simple_animations: ^3.1.1
  flutter_offline:      #
  sliding_sheet: ^0.5.0  
  flutter_signin_button:
  auth_buttons: 
  mk_drop_down_menu: ^1.1.0    #
  flutter_gradients: ^1.0.0+3    
  shimmer: ^2.0.0
  webview_flutter_plus:           ##
  dio: ^4.0.0
  image_gallery_saver: ^1.6.9        #
  get: ^4.1.4
  flutter_sticky_header: ^0.6.0
  html: ^0.15.0
  gbk2utf8: ^1.0.1
  firebase_crashlytics: ^2.0.4     #
  image_crop: ^0.4.0                 #
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  widgets_visibility_provider: ^3.0.1
  youtube_player_flutter: ^8.0.0       ##
  show_overlay: ^1.0.8
  loading_indicator: ^2.0.1
  sign_in_with_apple: ^3.0.0     #
  crypto: ^3.0.1         
  carousel_slider: ^4.0.0
  # firebase_app_check: ^0.0.1
  # flutter_facebook_auth: ^3.0.0
  flutter_login_facebook: ^1.0.1     #
  # google_mobile_ads: ^0.12.1+1
  # firebase_analytics: 
  # connectivity_plus: ^1.0.0
  connectivity: ^3.0.6
  lazy_load_scrollview: ^1.3.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.13.3
  flutter_launcher_icons: ^0.9.0
  

dev_dependencies:
  flutter_test: 
    sdk: flutter
  hive_generator:
  build_runner:    
  flutter_native_splash: 

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#1a1a1a"
  image: assets/logo.png
  android: true
  ios: true

flutter_icons:
  image_path: assets/stark-wg.png
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/icons/appbar_appicon.png
   - assets/icons/appbar_appicon_inverted.png
   - assets/icons/google_signin_button.png
   - assets/icons/google_sign_in_button.png
   - assets/images/appicon_rays.png
   - assets/icons/seperation_dot_icon.svg
   - assets/images/GIPHY_light.png
   - assets/images/GIPHY_dark.png
   - assets/images/Earth and Moon.svg
   - assets/images/Bad Gateway.svg
   - assets/images/No messages.svg
   - assets/images/Welcome.svg
   - assets/images/Message Sent.svg
   - assets/images/Searching.svg
   - assets/images/placeholder_image.jpg
   - assets/images/stark-bnb-icon-wa.png
   - assets/images/stark-bnb-icon-wi.png
   - assets/images/sign_in_image.png
   - assets/images/sign_in_image_w.png
   - assets/logo.png
   - assets/stark-wg.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Techna Sans Regular
      fonts:
        - asset: assets/fonts/TechnaSansRegular.ttf
    - family: Diskopia
      fonts:
        - asset: assets/fonts/Diskopia.ttf
    - family: Foo
      fonts:
        - asset: assets/fonts/Foo.ttf      
    - family: LostFish
      fonts:
        - asset: assets/fonts/LostFish.ttf
    - family: Georgia
      fonts:
        - asset: assets/fonts/Georgia.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
    - family: Yahoo Sans
      fonts:
        - asset: assets/fonts/yahoo_sans_regular.ttf
          weight: 400
        - asset: assets/fonts/yahoo_sans_medium.ttf
          weight: 500
    - family: Yahoo Sans Cond
      fonts:
        - asset: assets/fonts/yahoo_sans_cond_black.ttf
    - family: Lexend Deca
      fonts:
        - asset: assets/fonts/LexendDeca-Regular.ttf
    - family: Stark Sans
      fonts:
        - asset: assets/fonts/sans/SansBlack.ttf
          weight: 800
        - asset: assets/fonts/sans/SansBold.ttf
          weight: 600
        - asset: assets/fonts/sans/SansLight.ttf
          weight: 300
        - asset: assets/fonts/sans/SansMedium.ttf
          weight: 500
        - asset: assets/fonts/sans/SansRegular.ttf
          weight: 400
        - asset: assets/fonts/sans/SansThin.ttf
          weight: 200
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
